version: "3.1"
services:
  notebook:
    image: lecturing/dhbw-ds101-notebook:1.0
    #build:
    #  context: analysisEnvironment
    #  dockerfile: notebook.Dockerfile
    container_name: notebook
    volumes:
      - "./analysis:/home/jovyan/work"
      - "./data:/home/jovyan/data"
      - "./solutions:/home/jovyan/solutions"
    ports:
      - "8888:8888"
      - "4040:4040"
    command: jupyter notebook --allow-root
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on: 
      - mlflow
  mlflow:
   #build:
   #  context: analysisEnvironment
   #  dockerfile: mlflow.Dockerfile
   image: lecturing/dhbw-ds101-mlflow:1.0
   container_name: mlflow
   expose: 
      - "5000"
   ports:
     - "5000:5000"
  postgis:
   image: mdillon/postgis:11
   ports:
     - "5432:5432"
   volumes:
     - "./postgis/data:/data"
     - "./postgis/postgis:/var/lib/postgresql"
   environment:
     - POSTGRES_PASSWORD=analytics
     - POSTGRES_USER=analytics
     - POSTGRES_DB=analytics